### ISSUE TITLE
Subreddit support after /r/megalinks deprecation

### ISSUE THREAD

**Issue by andrewjmetzger** [samvk/snahp-it-forum-link-solver#1]
The subreddit /r/megalinks has now been removed by the reddit admins. Consider adding support for /r/megalinks2 instead (See PR #2). 

Alternatively, remove support for Reddit altogether, and instead focus on the Snahp.it forum. 

Discussion, comments, and suggestions welcome; thanks!

**Comment by andrewjmetzger** [comment]
Update: After some (admittedly brief) investigation, it seems /r/megalinks2 does not point users to content in the same way that /r/megalinks did (or, at all, really). 

I would suggest simply removing support for Reddit -- let me know if this is preferred and I will amend PR #2 as necessary.

**Comment by samvk** [comment]
Yeah I think the best thing for now is to simply remove support for Reddit just from the manifest.

**Comment by andrewjmetzger** [comment]
@samvk Excellent. I have updated the attached PR and removed Reddit support from the manifest.
