### ISSUE TITLE
Add support for newer Mega Folder links

### ISSUE THREAD

**Issue by andrewjmetzger** [samvk/snahp-it-forum-link-solver#5]
Newer mega folder links are not presently detected and decoded by the extension. These start with the following strings:

- Plain: `https://mega.nz/folder/`
- Base64: `aHR0cHM6Ly9tZWdhLm56L2ZvbGRlci8`
- Double Base64: `YUhSMGNITTZMeTl0WldkaExtNTZMMlp2YkdSbGNpOA`

Proposed Solution: Update the constants on [L31-L32 of forum/index.js](https://github.com/samvk/snahp-it-forum-link-solver/blob/fc630e311edd8daddc1d215b6036ea17807ac630/forum/index.js#L31-L32
) by appending the patterns above. Alternatively, add another set of constants, `megaFolderBase64Pattern` and `megaFolderBase64x2Pattern`, and update the `links` map accordingly.

**Comment by samvk** [comment]
Fixed in https://github.com/samvk/snahp-it-forum-link-solver/commit/18eaec29b79b8fe488d0ab8fb217023e54d37a8c.
