### ISSUE TITLE
Any chance for Firefox support?

### ISSUE THREAD

**Issue by Pocokk** [samvk/snahp-it-forum-link-solver#6]
Title basically, would it be possible to port over the extension to the Firefox browser?

**Comment by dephunk** [comment]
Would love a firefox version also!

**Comment by Pocokk** [comment]
bump.

**Comment by samvk** [comment]
https://addons.mozilla.org/en-US/firefox/addon/snahp-forum-link-solver/

**Comment by Pocokk** [comment]
Thank you.

**Comment by Pocokk** [comment]
Please switch the Link Protector from

https://links.snahp.it

to

https://lnk.snahp.eu

as the url has changed with the latest domain update.
